package yekonga

type DatabaseStructure = map[string]map[string]DatabaseCollectionFieldConfig

// DatabaseCollectionFieldConfig represents the provided metadata structure.
type DatabaseCollectionFieldConfig struct {
	Type       string   `json:"type"`
	Default    any      `json:"default,omitempty"`
	Required   bool     `json:"required,omitempty"`
	Options    []string `json:"options,omitempty"`
	Protected  bool     `json:"protected,omitempty"`
	ForeignKey string   `json:"foreignKey,omitempty"`
	Resource   string   `json:"resource,omitempty"`
}

var DefaultTenantDatabaseStructure DatabaseStructure = DatabaseStructure{
	"Tenants": {
		"id":              {Type: "ID", Default: nil, Required: false},
		"userId":          {Type: "ID", Default: nil, Required: false, ForeignKey: "User.id"},
		"name":            {Type: "String", Default: nil, Required: false},
		"description":     {Type: "String", Default: nil, Required: false},
		"logoUrl":         {Type: "URL", Default: nil, Required: false},
		"faviconUrl":      {Type: "URL", Default: nil, Required: false},
		"type":            {Type: "String", Default: "COMPANY", Required: false, Options: []string{"NGO", "COMPANY", "PRIVATE"}},
		"address":         {Type: "String", Default: nil, Required: false},
		"email":           {Type: "String", Default: nil, Required: false},
		"phone":           {Type: "String", Default: nil, Required: false},
		"website":         {Type: "String", Default: nil, Required: false},
		"domain":          {Type: "String", Default: nil, Required: false},
		"subdomain":       {Type: "String", Default: nil, Required: false},
		"customDomain":    {Type: "String", Default: nil, Required: false},
		"customSubdomain": {Type: "String", Default: nil, Required: false},
		"language":        {Type: "String", Default: "en", Required: false},
		"isApproved":      {Type: "Boolean", Default: false, Required: false},
		"status":          {Type: "String", Default: "active", Required: false, Options: []string{"active", "inactive"}},
		"createdAt":       {Type: "Date", Default: "now", Required: false},
	},
	"TenantConfigs": {
		"id":                {Type: "ID", Default: nil, Required: false},
		"tenantId":          {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"lightTheme":        {Type: "Any", Default: nil, Required: false},
		"darkTheme":         {Type: "Any", Default: nil, Required: false},
		"defaultTheme":      {Type: "String", Default: "lightTheme", Required: false},
		"smtp":              {Type: "Any", Default: nil, Required: false},
		"sms":               {Type: "Any", Default: nil, Required: false},
		"whatsapp":          {Type: "Any", Default: nil, Required: false},
		"publicCanRegister": {Type: "Boolean", Default: false, Required: false},
		"hasMembership":     {Type: "Boolean", Default: false, Required: false},
		"otherConfig":       {Type: "Any", Default: nil, Required: false},
		"language":          {Type: "String", Default: "en", Required: false},
	},
	"TenantFeatures": {
		"id":          {Type: "ID", Default: nil, Required: false},
		"tenantId":    {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"moduleName":  {Type: "String", Default: nil, Required: false},
		"featureCode": {Type: "String", Default: nil, Required: false},
		"enabled":     {Type: "Boolean", Default: true, Required: false},
	},
	"TenantUsers": {
		"id":        {Type: "ID", Default: nil, Required: false},
		"tenantId":  {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"userId":    {Type: "ID", Default: nil, Required: false, ForeignKey: "User.id"},
		"role":      {Type: "String", Default: "public", Required: false, Options: []string{"admin", "public"}},
		"status":    {Type: "String", Default: "active", Required: false, Options: []string{"active", "inactive"}},
		"createdAt": {Type: "Date", Default: "now", Required: false},
	},
}

var DefaultTenantCatchDatabaseStructure DatabaseStructure = DatabaseStructure{
	"TenantCatches": {
		"id":       {Type: "ID", Default: nil, Required: false},
		"tenantId": {Type: "ID", Default: nil, Required: false},
		"domain":   {Type: "String", Default: nil, Required: false},
	},
}

var DefaultAuthDatabaseStructure DatabaseStructure = DatabaseStructure{
	"Users": {
		"id":                 {Type: "ID", Default: nil, Required: false},
		"firstName":          {Type: "String", Default: nil, Required: false},
		"secondName":         {Type: "String", Default: nil, Required: false},
		"lastName":           {Type: "String", Default: nil, Required: false},
		"username":           {Type: "String", Default: nil, Required: false, Protected: false},
		"usernameType":       {Type: "String", Default: nil, Required: false, Options: []string{"name", "email", "phone", "whatsapp"}, Protected: false},
		"email":              {Type: "String", Default: nil, Required: false, Protected: false},
		"phone":              {Type: "String", Default: nil, Required: false, Protected: false},
		"whatsapp":           {Type: "String", Default: nil, Required: false, Protected: false},
		"profileUrl":         {Type: "URL", Default: nil, Required: false},
		"gender":             {Type: "String", Default: nil, Required: false, Options: []string{"male", "female"}},
		"dateOfBirth":        {Type: "Date", Default: nil, Required: false},
		"password":           {Type: "String", Default: nil, Required: false, Protected: true},
		"role":               {Type: "String", Default: nil, Required: false, Options: []string{"admin", "user"}},
		"token":              {Type: "String", Default: nil, Required: false, Protected: true},
		"googleToken":        {Type: "String", Default: nil, Required: false, Protected: true},
		"rememberToken":      {Type: "String", Default: nil, Required: false, Protected: true},
		"deviceToken":        {Type: "String", Default: nil, Required: false, Protected: true},
		"status":             {Type: "String", Default: "active", Required: false, Options: []string{"active", "inactive"}},
		"isActive":           {Type: "Boolean", Default: false, Required: false},
		"isBanned":           {Type: "Boolean", Default: false, Required: false},
		"isPhoneVerified":    {Type: "Boolean", Default: false, Required: false},
		"phoneVerifyCode":    {Type: "String", Default: nil, Required: false, Protected: true},
		"phoneVerifiedAt":    {Type: "Date", Default: nil, Required: false},
		"isEmailVerified":    {Type: "Boolean", Default: false, Required: false},
		"emailVerifyCode":    {Type: "String", Default: nil, Required: false, Protected: true},
		"emailVerifiedAt":    {Type: "Date", Default: nil, Required: false},
		"isWhatsappVerified": {Type: "Boolean", Default: false, Required: false},
		"whatsappVerifyCode": {Type: "String", Default: nil, Required: false, Protected: true},
		"whatsappVerifiedAt": {Type: "Date", Default: nil, Required: false},
		"otpCode":            {Type: "String", Default: nil, Required: false, Protected: true},
		"otpCreatedAt":       {Type: "Date", Default: nil, Required: false},
		"userType": {
			Type:     "String",
			Default:  "individual",
			Required: false,
			Options:  []string{"individual", "organization"},
		},
		"lastActive": {Type: "Date", Default: "now", Required: false},
		"createdAt":  {Type: "Date", Default: "now", Required: false},
		"updatedAt":  {Type: "Date", Default: "now", Required: false},
		"deletedAt":  {Type: "Date", Default: nil, Required: false},
	},
	"UserVerifications": {
		"id":            {Type: "ID", Default: nil, Required: false},
		"tenantId":      {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"userId":        {Type: "ID", Default: nil, Required: false, ForeignKey: "User.id"},
		"username":      {Type: "String", Default: nil, Required: false, Protected: true},
		"usernameType":  {Type: "String", Default: nil, Required: false, Options: []string{"name", "email", "phone", "whatsapp"}},
		"target":        {Type: "String", Default: nil, Required: false, Protected: true},
		"otpCode":       {Type: "String", Default: nil, Required: false, Protected: true},
		"otpCreatedAt":  {Type: "Date", Default: nil, Required: false, Protected: true},
		"otpVerifiedAt": {Type: "Date", Default: nil, Required: false},
		"count":         {Type: "Number", Default: 0, Required: false, Protected: true},
		"createdAt":     {Type: "Date", Default: "now", Required: false},
		"updatedAt":     {Type: "Date", Default: "now", Required: false},
	},
	"Profiles": {
		"id":          {Type: "ID", Default: nil, Required: false},
		"tenantId":    {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"userId":      {Type: "ID", Default: nil, Required: false, ForeignKey: "User.id"},
		"name":        {Type: "String", Default: nil, Required: false},
		"description": {Type: "String", Default: nil, Required: false},
		"profileUrl":  {Type: "URL", Default: nil, Required: false},
		"type":        {Type: "String", Default: nil, Required: false, Options: []string{"admin", "manager", "user"}},
		"address":     {Type: "String", Default: nil, Required: false},
		"email":       {Type: "String", Default: nil, Required: false},
		"phone":       {Type: "String", Default: nil, Required: false},
		"website":     {Type: "String", Default: nil, Required: false},
		"domain":      {Type: "String", Default: nil, Required: false},
		"subdomain":   {Type: "String", Default: nil, Required: false},
		"language":    {Type: "String", Default: "en", Required: false},
		"isPrivate":   {Type: "Boolean", Default: false, Required: false},
		"isApproved":  {Type: "Boolean", Default: false, Required: false},
		"status":      {Type: "String", Default: "active", Required: false, Options: []string{"active", "inactive"}},
		"deletedAt":   {Type: "Date", Default: nil, Required: false},
	},
	"ProfileUsers": {
		"id":        {Type: "ID", Default: nil, Required: false},
		"tenantId":  {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"profileId": {Type: "ID", Default: nil, Required: false, ForeignKey: "Profile.id"},
		"userId":    {Type: "ID", Default: nil, Required: false, ForeignKey: "User.id"},
		"role":      {Type: "String", Default: nil, Required: false, Options: []string{"manager", "user"}},
		"status":    {Type: "String", Default: "active", Required: false, Options: []string{"active", "inactive"}},
		"createdAt": {Type: "Date", Default: "now", Required: false},
	},
	"RefreshTokens": {
		"id":        {Type: "ID", Default: nil, Required: false},
		"tenantId":  {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"domain":    {Type: "String", Default: nil, Required: false},
		"profileId": {Type: "ID", Default: nil, Required: false, ForeignKey: "Profile.id"},
		"userId":    {Type: "ID", Default: nil, Required: false, ForeignKey: "User.id"},
		"adminId":   {Type: "ID", Default: nil, Required: false, ForeignKey: "User.id"},
		"tokenHash": {Type: "String", Default: nil, Required: false, Protected: true},
		"userAgent": {Type: "String", Default: nil, Required: false},
		"ipAddress": {Type: "String", Default: nil, Required: false},
		"revoked":   {Type: "Boolean", Default: false, Required: false},
		"expiresAt": {Type: "Date", Default: "now", Required: false},
	},
	"LoginAttempts": {
		"id":        {Type: "ID", Default: nil, Required: false},
		"tenantId":  {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"domain":    {Type: "String", Default: nil, Required: false},
		"profileId": {Type: "ID", Default: nil, Required: false, ForeignKey: "Profile.id"},
		"userId":    {Type: "ID", Default: nil, Required: false, ForeignKey: "User.id"},
		"username":  {Type: "String", Default: nil, Required: false},
		"status":    {Type: "String", Default: "success", Required: false, Options: []string{"success", "fail"}},
		"timestamp": {Type: "Date", Default: "now", Required: false},
	},
	"UserDevices": {
		"id":         {Type: "ID", Default: nil, Required: false},
		"tenantId":   {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"userId":     {Type: "ID", Default: nil, Required: false, ForeignKey: "User.id"},
		"deviceUuid": {Type: "String", Default: nil, Required: false},
		"type":       {Type: "Any", Default: nil, Required: false},
		"info":       {Type: "Any", Default: nil, Required: false},
		"status":     {Type: "String", Default: "active", Required: false, Options: []string{"active", "inactive"}},
		"createdAt":  {Type: "Date", Default: "now", Required: false},
	},
	"UserDeviceCommands": {
		"id":           {Type: "ID", Default: nil, Required: false},
		"tenantId":     {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"userDeviceId": {Type: "ID", Default: nil, Required: false, ForeignKey: "UserDevice.id"},
		"deviceUuid":   {Type: "String", Default: nil, Required: false},
		"action":       {Type: "String", Default: nil, Required: false},
		"type": {
			Type:     "String",
			Default:  "command",
			Required: false,
			Options:  []string{"command", "notification", "chat"},
		},
		"isSent":     {Type: "Boolean", Default: false, Required: false},
		"isReceived": {Type: "Boolean", Default: false, Required: false},
		"createdAt":  {Type: "Date", Default: "now", Required: false},
	},
	"AuthPermissions": {
		"id":          {Type: "ID", Default: nil, Required: false},
		"moduleName":  {Type: "String", Default: nil, Required: false},
		"group":       {Type: "String", Default: nil, Required: false},
		"code":        {Type: "String", Default: nil, Required: false},
		"name":        {Type: "String", Default: nil, Required: false},
		"description": {Type: "String", Default: nil, Required: false},
		"isVisible":   {Type: "Boolean", Default: true, Required: false},
	},
	"AuthGroups": {
		"id":          {Type: "ID", Default: nil, Required: false},
		"tenantId":    {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"profileId":   {Type: "ID", Default: nil, Required: false, ForeignKey: "Profile.id"},
		"moduleName":  {Type: "String", Default: nil, Required: false},
		"name":        {Type: "String", Default: nil, Required: false},
		"description": {Type: "String", Default: nil, Required: false},
	},
	"AuthGroupPermissions": {
		"id":               {Type: "ID", Default: nil, Required: false},
		"tenantId":         {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"authGroupId":      {Type: "ID", Default: nil, Required: false, ForeignKey: "AuthGroup.id"},
		"authPermissionId": {Type: "ID", Default: nil, Required: false, ForeignKey: "AuthPermission.id"},
	},
	"AuthUserPermissions": {
		"id":          {Type: "ID", Default: nil, Required: false},
		"tenantId":    {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"profileId":   {Type: "ID", Default: nil, Required: false, ForeignKey: "Profile.id"},
		"userId":      {Type: "ID", Default: nil, Required: false, ForeignKey: "User.id"},
		"authGroupId": {Type: "ID", Default: nil, Required: false, ForeignKey: "AuthGroup.id"},
		"moduleName":  {Type: "String", Default: nil, Required: false},
		"code":        {Type: "String", Default: nil, Required: false, ForeignKey: "AuthPermission.code"},
	},
	"TranslatorLanguages": {
		"id":     {Type: "ID", Default: nil, Required: false},
		"locale": {Type: "String", Default: nil, Required: false},
		"name":   {Type: "String", Default: nil, Required: false},
		"flag":   {Type: "String", Default: nil, Required: false},
		"status": {Type: "String", Default: "active", Required: false, Options: []string{"active", "inactive"}},
	},
	"TranslatorTranslations": {
		"id":                   {Type: "ID", Default: nil, Required: false},
		"translatorLanguageId": {Type: "ID", Default: nil, Required: false, ForeignKey: "TranslatorLanguage.id"},
		"locale":               {Type: "String", Default: nil, Required: false},
		"moduleName":           {Type: "String", Default: nil, Required: false},
		"group":                {Type: "String", Default: nil, Required: false},
		"item":                 {Type: "String", Default: nil, Required: false},
		"description":          {Type: "String", Default: nil, Required: false},
		"text":                 {Type: "String", Default: nil, Required: false},
		"unstable":             {Type: "String", Default: nil, Required: false},
		"locked":               {Type: "String", Default: nil, Required: false},
	},
	"Locations": {
		"id":        {Type: "ID", Default: nil, Required: false},
		"parentId":  {Type: "ID", Default: nil, Required: false, ForeignKey: "Location.id"},
		"name":      {Type: "String", Default: nil, Required: false},
		"shortCode": {Type: "String", Default: nil, Required: false},
		"phoneCode": {Type: "String", Default: nil, Required: false},
		"currency":  {Type: "String", Default: nil, Required: false},
		"flag":      {Type: "String", Default: nil, Required: false},
		"type": {
			Type:     "String",
			Default:  "region",
			Required: false,
			Options:  []string{"country", "region", "district", "ward"},
		},
		"latitude":  {Type: "Float", Default: nil, Required: false},
		"longitude": {Type: "Float", Default: nil, Required: false},
	},
}

var DefaultBillingDatabaseStructure DatabaseStructure = DatabaseStructure{
	"Modules": {
		"id":          {Type: "ID", Default: nil, Required: false},
		"moduleName":  {Type: "String", Default: nil, Required: false},
		"title":       {Type: "String", Default: nil, Required: false},
		"description": {Type: "String", Default: nil, Required: false},
		"enabled":     {Type: "Boolean", Default: true, Required: false},
	},
	"PricingPlans": {
		"id":           {Type: "ID", Default: nil, Required: false},
		"moduleId":     {Type: "ID", Default: nil, Required: false, ForeignKey: "Module.id"},
		"pricingType":  {Type: "String", Default: "flat", Required: false, Options: []string{"flat", "per_user", "per_unit", "metered"}},
		"billingCycle": {Type: "String", Default: "monthly", Required: false, Options: []string{"monthly", "yearly"}},
		"price":        {Type: "Float", Default: 0, Required: false},
		"trialDays":    {Type: "Number", Default: 30, Required: false},
		"graceDays":    {Type: "Number", Default: 7, Required: false},
	},
	"Subscriptions": {
		"id":                 {Type: "ID", Default: nil, Required: false},
		"tenantId":           {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"status":             {Type: "String", Default: "active", Required: false, Options: []string{"active", "grace", "trailing", "past_due", "canceled", "unpaid", "expired"}},
		"trialStart":         {Type: "Date", Default: nil, Required: false},
		"trialEnd":           {Type: "Date", Default: nil, Required: false},
		"currentPeriodStart": {Type: "Date", Default: nil, Required: false},
		"currentPeriodEnd":   {Type: "Date", Default: nil, Required: false},
		"gracePeriodEnd":     {Type: "Date", Default: nil, Required: false},
		"nextBillingDate":    {Type: "Date", Default: nil, Required: false},
		"canceledAt":         {Type: "Date", Default: nil, Required: false},
	},
	"SubscriptionItems": {
		"id":             {Type: "ID", Default: nil, Required: false},
		"tenantId":       {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"subscriptionId": {Type: "ID", Default: nil, Required: false, ForeignKey: "Subscription.id"},
		"moduleId":       {Type: "ID", Default: nil, Required: false, ForeignKey: "Module.id"},
		"pricingPlanId":  {Type: "ID", Default: nil, Required: false, ForeignKey: "PricingPlan.id"},
		"quantity":       {Type: "Float", Default: 0, Required: false},
	},
	"UsageRecords": {
		"id":          {Type: "ID", Default: nil, Required: false},
		"tenantId":    {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"moduleId":    {Type: "ID", Default: nil, Required: false, ForeignKey: "Module.id"},
		"quantity":    {Type: "Float", Default: 0, Required: false},
		"periodStart": {Type: "Date", Default: nil, Required: false},
		"periodEnd":   {Type: "Date", Default: nil, Required: false},
	},
	"Invoices": {
		"id":              {Type: "ID", Default: nil, Required: false},
		"tenantId":        {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"subscriptionId":  {Type: "ID", Default: nil, Required: false, ForeignKey: "Subscription.id"},
		"amountDue":       {Type: "Float", Default: 0, Required: false},
		"amountPaid":      {Type: "Float", Default: 0, Required: false},
		"amountRemaining": {Type: "Float", Default: 0, Required: false},
		"status":          {Type: "String", Default: "pending", Required: false, Options: []string{"paid", "pending", "partially_paid", "failed", "canceled"}},
		"dueDate":         {Type: "Date", Default: nil, Required: false},
		"paidDate":        {Type: "Date", Default: nil, Required: false},
	},
	"InvoiceItems": {
		"id":                 {Type: "ID", Default: nil, Required: false},
		"tenantId":           {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"invoiceId":          {Type: "ID", Default: nil, Required: false, ForeignKey: "Invoice.id"},
		"moduleId":           {Type: "ID", Default: nil, Required: false, ForeignKey: "Module.id"},
		"subscriptionItemId": {Type: "ID", Default: nil, Required: false, ForeignKey: "SubscriptionItem.id"},
		"description":        {Type: "String", Default: nil, Required: false},
		"pricingType":        {Type: "String", Default: "flat", Required: false, Options: []string{"flat", "per_user", "per_unit", "metered"}},
		"quantity":           {Type: "Float", Default: 0, Required: false},
		"unitPrice":          {Type: "Float", Default: 0, Required: false},
		"totalPrice":         {Type: "Float", Default: 0, Required: false},
		"currency":           {Type: "String", Default: nil, Required: false},
		"startPeriod":        {Type: "Date", Default: nil, Required: false},
		"endPeriod":          {Type: "Date", Default: nil, Required: false},
		"metadata":           {Type: "Any", Default: nil, Required: false},
		"createdAt":          {Type: "Date", Default: "now", Required: false},
	},
	"Payments": {
		"id":                {Type: "ID", Default: nil, Required: false},
		"tenantId":          {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"provider":          {Type: "String", Default: nil, Required: false},
		"providerPaymentId": {Type: "String", Default: nil, Required: false},
		"amount":            {Type: "Float", Default: 0, Required: false},
		"currency":          {Type: "String", Default: nil, Required: false},
		"status":            {Type: "String", Default: "pending", Required: false, Options: []string{"pending", "succeeded", "failed", "canceled", "refunded"}},
		"paymentMethod":     {Type: "String", Default: "card", Required: false, Options: []string{"card", "bank_transfer", "paypal", "crypto"}},
		"failureReason":     {Type: "String", Default: nil, Required: false},
		"paidAt":            {Type: "Date", Default: "now", Required: false},
		"refundedAt":        {Type: "Date", Default: nil, Required: false},
		"metadata":          {Type: "Any", Default: nil, Required: false},
		"updatedAt":         {Type: "Date", Default: "now", Required: false},
		"createdAt":         {Type: "Date", Default: "now", Required: false},
	},
	"PaymentAllocations": {
		"id":              {Type: "ID", Default: nil, Required: false},
		"tenantId":        {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"paymentId":       {Type: "String", Default: nil, Required: false, ForeignKey: "Payments.id"},
		"invoiceId":       {Type: "String", Default: nil, Required: false, ForeignKey: "Invoice.id"},
		"amountAllocated": {Type: "Float", Default: 0, Required: false},
		"createdAt":       {Type: "Date", Default: "now", Required: false},
	},
	"AccountCredits": {
		"id":        {Type: "ID", Default: nil, Required: false},
		"tenantId":  {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"paymentId": {Type: "String", Default: nil, Required: false, ForeignKey: "Payments.id"},
		"amount":    {Type: "Float", Default: 0, Required: false},
		"createdAt": {Type: "Date", Default: "now", Required: false},
	},
}

var DefaultExtraDatabaseStructure DatabaseStructure = DatabaseStructure{
	"Notifications": {
		"id":                {Type: "ID", Default: nil, Required: false},
		"tenantId":          {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"profileId":         {Type: "ID", Default: nil, Required: false, ForeignKey: "Profile.id"},
		"userId":            {Type: "ID", Default: nil, Required: false, ForeignKey: "User.id"},
		"senderName":        {Type: "String", Default: nil, Required: false},
		"referenceId":       {Type: "ID", Default: nil, Required: false},
		"referenceName":     {Type: "String", Default: nil, Required: false},
		"recipient":         {Type: "String", Default: nil, Required: false},
		"recipientName":     {Type: "String", Default: nil, Required: false},
		"replyTo":           {Type: "String", Default: nil, Required: false},
		"title":             {Type: "String", Default: nil, Required: false},
		"content":           {Type: "Any", Default: nil, Required: false},
		"link":              {Type: "String", Default: nil, Required: false},
		"attachment":        {Type: "String", Default: nil, Required: false},
		"trackingCode":      {Type: "String", Default: nil, Required: false},
		"type":              {Type: "String", Default: nil, Required: false, Options: []string{"mail", "sms", "push"}},
		"isSeen":            {Type: "Boolean", Default: false, Required: false},
		"status":            {Type: "String", Default: nil, Required: false, Options: []string{"submitted", "waiting", "delivered", "undelivered"}},
		"response":          {Type: "Any", Default: nil, Required: false},
		"responseReference": {Type: "String", Default: nil, Required: false},
		"timestamp":         {Type: "Date", Default: "now", Required: false},
	},
	"PushNotifications": {
		"id":             {Type: "ID", Default: nil, Required: false},
		"tenantId":       {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"profileId":      {Type: "ID", Default: nil, Required: false, ForeignKey: "Profile.id"},
		"userId":         {Type: "ID", Default: nil, Required: false, ForeignKey: "User.id"},
		"deviceId":       {Type: "ID", Default: nil, Required: false, ForeignKey: "UserDevice.id"},
		"title":          {Type: "String", Default: nil, Required: false},
		"body":           {Type: "String", Default: nil, Required: false},
		"iconUrl":        {Type: "URL", Default: nil, Required: false},
		"pictureUrl":     {Type: "URL", Default: nil, Required: false},
		"payload":        {Type: "String", Default: nil, Required: false},
		"action":         {Type: "String", Default: nil, Required: false},
		"actionTargetId": {Type: "Any", Default: nil, Required: false},
		"isDelivered":    {Type: "Boolean", Default: nil, Required: false},
		"status":         {Type: "String", Default: nil, Required: false, Options: []string{"waiting", "sent", "delivered"}},
		"createdAt":      {Type: "Date", Default: "now", Required: false},
		"updatedAt":      {Type: "Date", Default: "now", Required: false},
	},
	"SocketMessages": {
		"id":        {Type: "ID", Default: nil, Required: false},
		"tenantId":  {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"profileId": {Type: "ID", Default: nil, Required: false, ForeignKey: "Profile.id"},
		"userId":    {Type: "ID", Default: nil, Required: false, ForeignKey: "User.id"},
		"deviceId":  {Type: "ID", Default: nil, Required: false, ForeignKey: "UserDevice.id"},
		"namespace": {Type: "String", Default: nil, Required: false},
		"action":    {Type: "String", Default: nil, Required: false},
		"content":   {Type: "Any", Default: nil, Required: false},
		"status":    {Type: "String", Default: nil, Required: false, Options: []string{"waiting", "sent", "delivered"}},
		"createdAt": {Type: "Date", Default: "now", Required: false},
		"updatedAt": {Type: "Date", Default: "now", Required: false},
	},
	"AuditTrails": {
		"id":         {Type: "ID", Default: nil, Required: false},
		"tenantId":   {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"profileId":  {Type: "ID", Default: nil, Required: false, ForeignKey: "Profile.id"},
		"userId":     {Type: "ID", Default: nil, Required: false, ForeignKey: "User.id"},
		"action":     {Type: "String", Default: nil, Required: false},
		"documentId": {Type: "ID", Default: nil, Required: false},
		"collection": {Type: "String", Default: nil, Required: false},
		"model":      {Type: "String", Default: nil, Required: false},
		"newValues":  {Type: "Any", Default: nil, Required: false},
		"oldValues":  {Type: "Any", Default: nil, Required: false},
		"ipAddress":  {Type: "String", Default: nil, Required: false},
		"browser":    {Type: "Any", Default: nil, Required: false},
		"userAgent":  {Type: "String", Default: nil, Required: false},
		"createdAt":  {Type: "Date", Default: "now", Required: false},
	},
	"Reports": {
		"id":          {Type: "ID", Default: nil, Required: false},
		"tenantId":    {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"userId":      {Type: "ID", Default: nil, Required: false, ForeignKey: "User.id"},
		"profileId":   {Type: "ID", Default: nil, Required: false, ForeignKey: "Profile.id"},
		"name":        {Type: "String", Default: nil, Required: false},
		"description": {Type: "String", Default: nil, Required: false},
		"data":        {Type: "Any", Default: nil, Required: false},
		"isPrivate":   {Type: "Boolean", Default: nil, Required: false},
		"isDashboard": {Type: "Boolean", Default: nil, Required: false},
		"sendEmail":   {Type: "Boolean", Default: nil, Required: false},
		"emails":      {Type: "Any", Default: nil, Required: false},
		"createdAt":   {Type: "Date", Default: "now", Required: false},
	},
	"ChatGroups": {
		"id":              {Type: "ID", Default: nil, Required: false},
		"tenantId":        {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"profileId":       {Type: "ID", Default: nil, Required: false, ForeignKey: "Profile.id"},
		"parentReference": {Type: "ID", Default: nil, Required: false},
		"reference":       {Type: "ID", Default: nil, Required: false},
		"title":           {Type: "String", Default: nil, Required: false},
		"description":     {Type: "String", Default: nil, Required: false},
		"members":         {Type: "{ID}", Default: []string{}, Required: false, ForeignKey: "ChatGroupMember.id"},
		"type": {
			Type:     "String",
			Default:  "public",
			Required: false,
			Options:  []string{"private", "public", "general"},
		},
		"timestamp": {Type: "Date", Default: "now", Required: false},
	},
	"ChatGroupMembers": {
		"id":              {Type: "ID", Default: nil, Required: false},
		"tenantId":        {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"reference":       {Type: "ID", Default: nil, Required: false},
		"userId":          {Type: "ID", Default: nil, Required: false, Resource: "Users.id"},
		"userReferenceId": {Type: "ID", Default: nil, Required: false},
		"name":            {Type: "String", Default: nil, Required: false},
		"profileUrl":      {Type: "String", Default: nil, Required: false},
		"isAdmin":         {Type: "Boolean", Default: false, Required: false},
		"isOwner":         {Type: "Boolean", Default: false, Required: false},
		"timestamp":       {Type: "Date", Default: "now", Required: false},
	},
	"ChatMessages": {
		"id":                {Type: "ID", Default: nil, Required: false},
		"tenantId":          {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"chatGroupId":       {Type: "ID", Default: nil, Required: false, ForeignKey: "ChatGroup.id"},
		"chatGroupMemberId": {Type: "ID", Default: nil, Required: false, ForeignKey: "ChatGroupMember.id"},
		"content":           {Type: "String", Default: nil, Required: false},
		"media":             {Type: "Any", Default: nil, Required: false},
		"mediaReference":    {Type: "String", Default: nil, Required: false},
		"type": {
			Type:     "String",
			Default:  "text",
			Required: false,
			Options:  []string{"text", "image", "location", "document", "video", "audio"},
		},
		"timestamp": {Type: "Date", Default: "now", Required: false},
	},
	"ChatMessageStates": {
		"id":                {Type: "ID", Default: nil, Required: false},
		"tenantId":          {Type: "ID", Default: nil, Required: false, ForeignKey: "Tenant.id"},
		"chatMessageId":     {Type: "ID", Default: nil, Required: false, ForeignKey: "ChatMessage.id"},
		"chatGroupMemberId": {Type: "ID", Default: nil, Required: false, ForeignKey: "ChatGroupMember.id"},
		"sent":              {Type: "Boolean", Default: false, Required: false},
		"sentDate":          {Type: "Date", Default: nil, Required: false},
		"received":          {Type: "Boolean", Default: false, Required: false},
		"receivedDate":      {Type: "Date", Default: nil, Required: false},
		"opened":            {Type: "Boolean", Default: false, Required: false},
		"openedDate":        {Type: "Date", Default: nil, Required: false},
		"timestamp":         {Type: "Date", Default: "now", Required: false},
	},
}
