package yekonga

var DefaultTenantDatabaseStructure DatabaseStructure = DatabaseStructure{
	"Tenants": map[string]CollectionFieldConfig{
		"id":              {Kind: "ID", DefaultValue: nil, Required: false},
		"userId":          {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"name":            {Kind: "String", DefaultValue: nil, Required: false},
		"description":     {Kind: "String", DefaultValue: nil, Required: false},
		"logoUrl":         {Kind: "URL", DefaultValue: nil, Required: false},
		"faviconUrl":      {Kind: "URL", DefaultValue: nil, Required: false},
		"type":            {Kind: "String", DefaultValue: "COMPANY", Required: false, Options: []string{"NGO", "COMPANY", "PRIVATE"}},
		"address":         {Kind: "String", DefaultValue: nil, Required: false},
		"email":           {Kind: "String", DefaultValue: nil, Required: false},
		"phone":           {Kind: "String", DefaultValue: nil, Required: false},
		"website":         {Kind: "String", DefaultValue: nil, Required: false},
		"domain":          {Kind: "String", DefaultValue: nil, Required: false},
		"subdomain":       {Kind: "String", DefaultValue: nil, Required: false},
		"customDomain":    {Kind: "String", DefaultValue: nil, Required: false},
		"customSubdomain": {Kind: "String", DefaultValue: nil, Required: false},
		"language":        {Kind: "String", DefaultValue: "en", Required: false},
		"isApproved":      {Kind: "Boolean", DefaultValue: false, Required: false},
		"status":          {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"active", "inactive"}},
		"createdAt":       {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"TenantConfigs": map[string]CollectionFieldConfig{
		"id":                {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":          {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"lightTheme":        {Kind: "Any", DefaultValue: nil, Required: false},
		"darkTheme":         {Kind: "Any", DefaultValue: nil, Required: false},
		"defaultTheme":      {Kind: "String", DefaultValue: "lightTheme", Required: false},
		"smtp":              {Kind: "Any", DefaultValue: nil, Required: false},
		"sms":               {Kind: "Any", DefaultValue: nil, Required: false},
		"whatsapp":          {Kind: "Any", DefaultValue: nil, Required: false},
		"publicCanRegister": {Kind: "Boolean", DefaultValue: false, Required: false},
		"hasMembership":     {Kind: "Boolean", DefaultValue: false, Required: false},
		"otherConfig":       {Kind: "Any", DefaultValue: nil, Required: false},
		"language":          {Kind: "String", DefaultValue: "en", Required: false},
	},
	"TenantFeatures": map[string]CollectionFieldConfig{
		"id":          {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"moduleName":  {Kind: "String", DefaultValue: nil, Required: false},
		"featureCode": {Kind: "String", DefaultValue: nil, Required: false},
		"enabled":     {Kind: "Boolean", DefaultValue: true, Required: false},
	},
	"TenantUsers": map[string]CollectionFieldConfig{
		"id":        {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"userId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"role":      {Kind: "String", DefaultValue: "public", Required: false, Options: []string{"admin", "public"}},
		"status":    {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"active", "inactive"}},
		"createdAt": {Kind: "Date", DefaultValue: "now", Required: false},
	},
}

var DefaultTenantCatchDatabaseStructure DatabaseStructure = DatabaseStructure{
	"TenantCatches": map[string]CollectionFieldConfig{
		"id":       {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId": {Kind: "ID", DefaultValue: nil, Required: false},
		"domain":   {Kind: "String", DefaultValue: nil, Required: false},
	},
}

var DefaultAuthDatabaseStructure DatabaseStructure = DatabaseStructure{
	"Users": map[string]CollectionFieldConfig{
		"id":                 {Kind: "ID", DefaultValue: nil, Required: false},
		"firstName":          {Kind: "String", DefaultValue: nil, Required: false},
		"secondName":         {Kind: "String", DefaultValue: nil, Required: false},
		"lastName":           {Kind: "String", DefaultValue: nil, Required: false},
		"username":           {Kind: "String", DefaultValue: nil, Required: false, Protected: false},
		"usernameType":       {Kind: "String", DefaultValue: nil, Required: false, Protected: false, Options: []string{"name", "email", "phone", "whatsapp"}},
		"email":              {Kind: "String", DefaultValue: nil, Required: false, Protected: false},
		"phone":              {Kind: "String", DefaultValue: nil, Required: false, Protected: false},
		"whatsapp":           {Kind: "String", DefaultValue: nil, Required: false, Protected: false},
		"profileUrl":         {Kind: "URL", DefaultValue: nil, Required: false},
		"gender":             {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"male", "female"}},
		"dateOfBirth":        {Kind: "Date", DefaultValue: nil, Required: false},
		"password":           {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"role":               {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"admin", "user"}},
		"token":              {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"googleToken":        {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"rememberToken":      {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"deviceToken":        {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"status":             {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"active", "inactive"}},
		"isActive":           {Kind: "Boolean", DefaultValue: false, Required: false},
		"isBanned":           {Kind: "Boolean", DefaultValue: false, Required: false},
		"isPhoneVerified":    {Kind: "Boolean", DefaultValue: false, Required: false},
		"phoneVerifyCode":    {Kind: "String", DefaultValue: false, Required: false, Protected: true},
		"phoneVerifiedAt":    {Kind: "Date", DefaultValue: nil, Required: false},
		"isEmailVerified":    {Kind: "Boolean", DefaultValue: false, Required: false},
		"emailVerifyCode":    {Kind: "String", DefaultValue: false, Required: false, Protected: true},
		"emailVerifiedAt":    {Kind: "Date", DefaultValue: nil, Required: false},
		"isWhatsappVerified": {Kind: "Boolean", DefaultValue: false, Required: false},
		"whatsappVerifyCode": {Kind: "String", DefaultValue: false, Required: false, Protected: true},
		"whatsappVerifiedAt": {Kind: "Date", DefaultValue: nil, Required: false},
		"otpCode":            {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"otpCreatedAt":       {Kind: "Date", DefaultValue: nil, Required: false},
		"userType":           {Kind: "String", DefaultValue: "individual", Required: false, Options: []string{"individual", "organization"}},
		"lastActive":         {Kind: "Date", DefaultValue: "now", Required: false},
		"createdAt":          {Kind: "Date", DefaultValue: "now", Required: false},
		"updatedAt":          {Kind: "Date", DefaultValue: "now", Required: false},
		"deletedAt":          {Kind: "Date", DefaultValue: nil, Required: false},
	},
	"UserVerifications": map[string]CollectionFieldConfig{
		"id":            {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":      {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"userId":        {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"username":      {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"usernameType":  {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"name", "email", "phone", "whatsapp"}},
		"target":        {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"otpCode":       {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"otpCreatedAt":  {Kind: "Date", DefaultValue: nil, Required: false, Protected: true},
		"otpVerifiedAt": {Kind: "Date", DefaultValue: nil, Required: false},
		"count":         {Kind: "Number", DefaultValue: 0, Required: false, Protected: true},
		"createdAt":     {Kind: "Date", DefaultValue: "now", Required: false},
		"updatedAt":     {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"Profiles": map[string]CollectionFieldConfig{
		"id":          {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"userId":      {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"name":        {Kind: "String", DefaultValue: nil, Required: false},
		"description": {Kind: "String", DefaultValue: nil, Required: false},
		"profileUrl":  {Kind: "URL", DefaultValue: nil, Required: false},
		"type":        {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"admin", "manager", "user"}},
		"address":     {Kind: "String", DefaultValue: nil, Required: false},
		"email":       {Kind: "String", DefaultValue: nil, Required: false},
		"phone":       {Kind: "String", DefaultValue: nil, Required: false},
		"website":     {Kind: "String", DefaultValue: nil, Required: false},
		"domain":      {Kind: "String", DefaultValue: nil, Required: false},
		"subdomain":   {Kind: "String", DefaultValue: nil, Required: false},
		"language":    {Kind: "String", DefaultValue: "en", Required: false},
		"isPrivate":   {Kind: "Boolean", DefaultValue: false, Required: false},
		"isApproved":  {Kind: "Boolean", DefaultValue: false, Required: false},
		"status":      {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"active", "inactive"}},
		"deletedAt":   {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"ProfileUsers": map[string]CollectionFieldConfig{
		"id":        {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"profileId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"userId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"role":      {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"manager", "user"}},
		"status":    {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"active", "inactive"}},
		"createdAt": {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"RefreshTokens": map[string]CollectionFieldConfig{
		"id":        {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"domain":    {Kind: "String", DefaultValue: nil, Required: false},
		"profileId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"userId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"adminId":   {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"tokenHash": {Kind: "String", DefaultValue: nil, Required: false, Protected: true},
		"userAgent": {Kind: "String", DefaultValue: nil, Required: false},
		"ipAddress": {Kind: "String", DefaultValue: nil, Required: false},
		"revoked":   {Kind: "Boolean", DefaultValue: false, Required: false},
		"expiresAt": {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"LoginAttempts": map[string]CollectionFieldConfig{
		"id":        {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"domain":    {Kind: "String", DefaultValue: nil, Required: false},
		"profileId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"userId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"username":  {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"success", "fail"}},
		"status":    {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"success", "fail"}},
		"timestamp": {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"UserDevices": map[string]CollectionFieldConfig{
		"id":         {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":   {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"userId":     {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"deviceUuid": {Kind: "String", DefaultValue: nil, Required: false},
		"type":       {Kind: "Any", DefaultValue: nil, Required: false},
		"info":       {Kind: "Any", DefaultValue: nil, Required: false},
		"status":     {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"active", "inactive"}},
		"createdAt":  {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"UserDeviceCommands": map[string]CollectionFieldConfig{
		"id":           {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":     {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"userDeviceId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "UserDevice", Key: "id"}},
		"deviceUuid":   {Kind: "String", DefaultValue: nil, Required: false},
		"action":       {Kind: "String", DefaultValue: nil, Required: false},
		"type":         {Kind: "String", DefaultValue: "command", Required: false, Options: []string{"command", "notification", "chat"}},
		"isSent":       {Kind: "Boolean", DefaultValue: false, Required: false},
		"isReceived":   {Kind: "Boolean", DefaultValue: false, Required: false},
		"createdAt":    {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"AuthPermissions": map[string]CollectionFieldConfig{
		"id":          {Kind: "ID", DefaultValue: nil, Required: false},
		"moduleName":  {Kind: "String", DefaultValue: nil, Required: false},
		"group":       {Kind: "String", DefaultValue: nil, Required: false},
		"code":        {Kind: "String", DefaultValue: nil, Required: false},
		"name":        {Kind: "String", DefaultValue: nil, Required: false},
		"description": {Kind: "String", DefaultValue: nil, Required: false},
		"isVisible":   {Kind: "Boolean", DefaultValue: true, Required: false},
	},
	"AuthGroups": map[string]CollectionFieldConfig{
		"id":          {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"profileId":   {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"moduleName":  {Kind: "String", DefaultValue: nil, Required: false},
		"name":        {Kind: "String", DefaultValue: nil, Required: false},
		"description": {Kind: "String", DefaultValue: nil, Required: false},
	},
	"AuthGroupPermissions": map[string]CollectionFieldConfig{
		"id":               {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":         {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"authGroupId":      {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "AuthGroup", Key: "id"}},
		"authPermissionId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "AuthPermission", Key: "id"}},
	},
	"AuthUserPermissions": map[string]CollectionFieldConfig{
		"id":          {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"profileId":   {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"userId":      {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"authGroupId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "AuthGroup", Key: "id"}},
		"moduleName":  {Kind: "String", DefaultValue: nil, Required: false},
		"code":        {Kind: "String", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "AuthPermission", Key: "code"}},
	},
	"TranslatorLanguages": map[string]CollectionFieldConfig{
		"id":     {Kind: "ID", DefaultValue: nil, Required: false},
		"locale": {Kind: "String", DefaultValue: nil, Required: false},
		"name":   {Kind: "String", DefaultValue: nil, Required: false},
		"flag":   {Kind: "String", DefaultValue: nil, Required: false},
		"status": {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"active", "inactive"}},
	},
	"TranslatorTranslations": map[string]CollectionFieldConfig{
		"id":                   {Kind: "ID", DefaultValue: nil, Required: false},
		"translatorLanguageId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "TranslatorLanguage", Key: "id"}},
		"locale":               {Kind: "String", DefaultValue: nil, Required: false},
		"moduleName":           {Kind: "String", DefaultValue: nil, Required: false},
		"group":                {Kind: "String", DefaultValue: nil, Required: false},
		"item":                 {Kind: "String", DefaultValue: nil, Required: false},
		"description":          {Kind: "String", DefaultValue: nil, Required: false},
		"text":                 {Kind: "String", DefaultValue: nil, Required: false},
		"unstable":             {Kind: "String", DefaultValue: nil, Required: false},
		"locked":               {Kind: "String", DefaultValue: nil, Required: false},
	},
	"Locations": map[string]CollectionFieldConfig{
		"id":        {Kind: "ID", DefaultValue: nil, Required: false},
		"parentId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Location", Key: "id"}},
		"name":      {Kind: "String", DefaultValue: nil, Required: false},
		"shortCode": {Kind: "String", DefaultValue: nil, Required: false},
		"phoneCode": {Kind: "String", DefaultValue: nil, Required: false},
		"currency":  {Kind: "String", DefaultValue: nil, Required: false},
		"flag":      {Kind: "String", DefaultValue: nil, Required: false},
		"type":      {Kind: "String", DefaultValue: "region", Required: false, Options: []string{"country", "region", "district", "ward"}},
		"latitude":  {Kind: "Float", DefaultValue: nil, Required: false},
		"longitude": {Kind: "Float", DefaultValue: nil, Required: false},
	},
}

var DefaultBillingDatabaseStructure DatabaseStructure = DatabaseStructure{
	"Modules": map[string]CollectionFieldConfig{
		"id":          {Kind: "ID", DefaultValue: nil, Required: false},
		"moduleName":  {Kind: "String", DefaultValue: nil, Required: false},
		"title":       {Kind: "String", DefaultValue: nil, Required: false},
		"description": {Kind: "String", DefaultValue: nil, Required: false},
		"enabled":     {Kind: "Boolean", DefaultValue: true, Required: false},
	},
	"PricingPlans": map[string]CollectionFieldConfig{
		"id":           {Kind: "ID", DefaultValue: nil, Required: false},
		"moduleId":     {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Module", Key: "id"}},
		"pricingType":  {Kind: "String", DefaultValue: "flat", Required: false, Options: []string{"flat", "per_user", "per_unit", "metered"}},
		"billingCycle": {Kind: "String", DefaultValue: "flat", Required: false, Options: []string{"monthly", "yearly"}},
		"price":        {Kind: "Float", DefaultValue: 0, Required: false},
		"trialDays":    {Kind: "Number", DefaultValue: 30, Required: false},
		"graceDays":    {Kind: "Number", DefaultValue: 7, Required: false},
	},
	"Subscriptions": map[string]CollectionFieldConfig{
		"id":                 {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":           {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"status":             {Kind: "String", DefaultValue: "flat", Required: false, Options: []string{"active", "grace", "trailing", "past_due", "canceled", "unpaid", "expired"}},
		"trialStart":         {Kind: "Date", DefaultValue: nil, Required: false},
		"trialEnd":           {Kind: "Date", DefaultValue: nil, Required: false},
		"currentPeriodStart": {Kind: "Date", DefaultValue: nil, Required: false},
		"currentPeriodEnd":   {Kind: "Date", DefaultValue: nil, Required: false},
		"gracePeriodEnd":     {Kind: "Date", DefaultValue: nil, Required: false},
		"nextBillingDate":    {Kind: "Date", DefaultValue: nil, Required: false},
		"canceledAt":         {Kind: "Date", DefaultValue: nil, Required: false},
	},
	"SubscriptionItems": map[string]CollectionFieldConfig{
		"id":             {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":       {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"subscriptionId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Subscription", Key: "id"}},
		"moduleId":       {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Module", Key: "id"}},
		"pricingPlanId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "PricingPlan", Key: "id"}},
		"quantity":       {Kind: "Float", DefaultValue: 0, Required: false},
	},
	"UsageRecords": map[string]CollectionFieldConfig{
		"id":          {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"moduleId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Module", Key: "id"}},
		"quantity":    {Kind: "Float", DefaultValue: 0, Required: false},
		"periodStart": {Kind: "Date", DefaultValue: nil, Required: false},
		"periodEnd":   {Kind: "Date", DefaultValue: nil, Required: false},
	},
	"Invoices": map[string]CollectionFieldConfig{
		"id":              {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":        {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"subscriptionId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Subscription", Key: "id"}},
		"amountDue":       {Kind: "Float", DefaultValue: 0, Required: false},
		"amountPaid":      {Kind: "Float", DefaultValue: 0, Required: false},
		"amountRemaining": {Kind: "Float", DefaultValue: 0, Required: false},
		"status":          {Kind: "String", DefaultValue: "flat", Required: false, Options: []string{"paid", "pending", "partially_paid", "failed", "canceled"}},
		"dueDate":         {Kind: "Date", DefaultValue: nil, Required: false},
		"paidDate":        {Kind: "Date", DefaultValue: nil, Required: false},
	},
	"InvoiceItems": map[string]CollectionFieldConfig{
		"id":                 {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":           {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"invoiceId":          {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Invoice", Key: "id"}},
		"moduleId":           {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Module", Key: "id"}},
		"subscriptionItemId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "SubscriptionItem", Key: "id"}},
		"description":        {Kind: "String", DefaultValue: nil, Required: false},
		"pricingType":        {Kind: "String", DefaultValue: "flat", Required: false, Options: []string{"flat", "per_user", "per_unit", "metered"}},
		"quantity":           {Kind: "Float", DefaultValue: 0, Required: false},
		"unitPrice":          {Kind: "Float", DefaultValue: 0, Required: false},
		"totalPrice":         {Kind: "Float", DefaultValue: 0, Required: false},
		"currency":           {Kind: "String", DefaultValue: nil, Required: false},
		"startPeriod":        {Kind: "Date", DefaultValue: nil, Required: false},
		"endPeriod":          {Kind: "Date", DefaultValue: nil, Required: false},
		"metadata":           {Kind: "Any", DefaultValue: nil, Required: false},
		"createdAt":          {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"Payments": map[string]CollectionFieldConfig{
		"id":                {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":          {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"provider":          {Kind: "String", DefaultValue: nil, Required: false},
		"providerPaymentId": {Kind: "String", DefaultValue: nil, Required: false},
		"amount":            {Kind: "Float", DefaultValue: 0, Required: false},
		"currency":          {Kind: "String", DefaultValue: nil, Required: false},
		"status":            {Kind: "String", DefaultValue: "flat", Required: false, Options: []string{"pending", "succeeded", "failed", "canceled", "refunded"}},
		"paymentMethod":     {Kind: "String", DefaultValue: "flat", Required: false, Options: []string{"card", "bank_transfer", "paypal", "crypto"}},
		"failureReason":     {Kind: "String", DefaultValue: nil, Required: false},
		"paidAt":            {Kind: "Date", DefaultValue: "now", Required: false},
		"refundedAt":        {Kind: "Date", DefaultValue: nil, Required: false},
		"metadata":          {Kind: "Any", DefaultValue: nil, Required: false},
		"updatedAt":         {Kind: "Date", DefaultValue: "now", Required: false},
		"createdAt":         {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"PaymentAllocations": map[string]CollectionFieldConfig{
		"id":              {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":        {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"paymentId":       {Kind: "String", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Payments", Key: "id"}},
		"invoiceId":       {Kind: "String", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Invoice", Key: "id"}},
		"amountAllocated": {Kind: "Float", DefaultValue: 0, Required: false},
		"createdAt":       {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"AccountCredits": map[string]CollectionFieldConfig{
		"id":        {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"paymentId": {Kind: "String", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Payments", Key: "id"}},
		"amount":    {Kind: "Float", DefaultValue: 0, Required: false},
		"createdAt": {Kind: "Date", DefaultValue: "now", Required: false},
	},
}

var DefaultExtraDatabaseStructure DatabaseStructure = DatabaseStructure{
	"Notifications": map[string]CollectionFieldConfig{
		"id":                {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":          {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"profileId":         {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"userId":            {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"senderName":        {Kind: "String", DefaultValue: nil, Required: false},
		"referenceId":       {Kind: "ID", DefaultValue: nil, Required: false},
		"referenceName":     {Kind: "String", DefaultValue: nil, Required: false},
		"recipient":         {Kind: "String", DefaultValue: nil, Required: false},
		"recipientName":     {Kind: "String", DefaultValue: nil, Required: false},
		"replyTo":           {Kind: "String", DefaultValue: nil, Required: false},
		"title":             {Kind: "String", DefaultValue: nil, Required: false},
		"content":           {Kind: "Any", DefaultValue: nil, Required: false},
		"link":              {Kind: "String", DefaultValue: nil, Required: false},
		"attachment":        {Kind: "String", DefaultValue: nil, Required: false},
		"trackingCode":      {Kind: "String", DefaultValue: nil, Required: false},
		"type":              {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"mail", "sms", "push"}},
		"isSeen":            {Kind: "Boolean", DefaultValue: false, Required: false},
		"status":            {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"submitted", "waiting", "delivered", "undelivered"}},
		"response":          {Kind: "Any", DefaultValue: nil, Required: false},
		"responseReference": {Kind: "String", DefaultValue: nil, Required: false},
		"timestamp":         {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"PushNotifications": map[string]CollectionFieldConfig{
		"id":             {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":       {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"profileId":      {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"userId":         {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"deviceId":       {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "UserDevice", Key: "id"}},
		"title":          {Kind: "String", DefaultValue: nil, Required: false},
		"body":           {Kind: "String", DefaultValue: nil, Required: false},
		"iconUrl":        {Kind: "URL", DefaultValue: nil, Required: false},
		"pictureUrl":     {Kind: "URL", DefaultValue: nil, Required: false},
		"payload":        {Kind: "String", DefaultValue: nil, Required: false},
		"action":         {Kind: "String", DefaultValue: nil, Required: false},
		"actionTargetId": {Kind: "Any", DefaultValue: nil, Required: false},
		"isDelivered":    {Kind: "Boolean", DefaultValue: nil, Required: false},
		"status":         {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"waiting", "sent", "delivered"}},
		"createdAt":      {Kind: "Date", DefaultValue: "now", Required: false},
		"updatedAt":      {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"SocketMessages": map[string]CollectionFieldConfig{
		"id":        {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"profileId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"userId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"deviceId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "UserDevice", Key: "id"}},
		"namespace": {Kind: "String", DefaultValue: nil, Required: false},
		"action":    {Kind: "String", DefaultValue: nil, Required: false},
		"content":   {Kind: "Any", DefaultValue: nil, Required: false},
		"status":    {Kind: "String", DefaultValue: nil, Required: false, Options: []string{"waiting", "sent", "delivered"}},
		"createdAt": {Kind: "Date", DefaultValue: "now", Required: false},
		"updatedAt": {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"AuditTrails": map[string]CollectionFieldConfig{
		"id":         {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":   {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"profileId":  {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"userId":     {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"action":     {Kind: "String", DefaultValue: nil, Required: false},
		"documentId": {Kind: "ID", DefaultValue: nil, Required: false},
		"collection": {Kind: "String", DefaultValue: nil, Required: false},
		"model":      {Kind: "String", DefaultValue: nil, Required: false},
		"newValues":  {Kind: "Any", DefaultValue: nil, Required: false},
		"oldValues":  {Kind: "Any", DefaultValue: nil, Required: false},
		"ipAddress":  {Kind: "String", DefaultValue: nil, Required: false},
		"browser":    {Kind: "Any", DefaultValue: nil, Required: false},
		"userAgent":  {Kind: "String", DefaultValue: nil, Required: false},
		"createdAt":  {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"Reports": map[string]CollectionFieldConfig{
		"id":          {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":    {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"userId":      {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "User", Key: "id"}},
		"profileId":   {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"name":        {Kind: "String", DefaultValue: nil, Required: false},
		"description": {Kind: "String", DefaultValue: nil, Required: false},
		"data":        {Kind: "Any", DefaultValue: nil, Required: false},
		"isPrivate":   {Kind: "Boolean", DefaultValue: nil, Required: false},
		"isDashboard": {Kind: "Boolean", DefaultValue: nil, Required: false},
		"sendEmail":   {Kind: "Boolean", DefaultValue: nil, Required: false},
		"emails":      {Kind: "Any", DefaultValue: nil, Required: false},
		"createdAt":   {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"ChatGroups": map[string]CollectionFieldConfig{
		"id":              {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":        {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"profileId":       {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Profile", Key: "id"}},
		"parentReference": {Kind: "ID", DefaultValue: nil, Required: false},
		"reference":       {Kind: "ID", DefaultValue: nil, Required: false},
		"title":           {Kind: "String", DefaultValue: nil, Required: false},
		"description":     {Kind: "String", DefaultValue: nil, Required: false},
		"members":         {Kind: "{ID}", DefaultValue: []string{}, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "ChatGroupMember"}},
		"type":            {Kind: "String", DefaultValue: "public", Required: false, Options: []string{"private", "public", "general"}},
		"timestamp":       {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"ChatGroupMembers": map[string]CollectionFieldConfig{
		"id":              {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":        {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"reference":       {Kind: "ID", DefaultValue: nil, Required: false},
		"userId":          {Kind: "ID", DefaultValue: nil, Required: false},
		"userReferenceId": {Kind: "ID", DefaultValue: nil, Required: false},
		"name":            {Kind: "String", DefaultValue: nil, Required: false},
		"profileUrl":      {Kind: "String", DefaultValue: nil, Required: false},
		"isAdmin":         {Kind: "Boolean", DefaultValue: false, Required: false},
		"isOwner":         {Kind: "Boolean", DefaultValue: false, Required: false},
		"timestamp":       {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"ChatMessages": map[string]CollectionFieldConfig{
		"id":                {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":          {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"chatGroupId":       {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "ChatGroup"}},
		"chatGroupMemberId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "ChatGroupMember", Key: "id"}},
		"content":           {Kind: "String", DefaultValue: nil, Required: false},
		"media":             {Kind: "Any", DefaultValue: nil, Required: false},
		"mediaReference":    {Kind: "String", DefaultValue: nil, Required: false},
		"type":              {Kind: "String", DefaultValue: "active", Required: false, Options: []string{"text", "image", "location", "document", "video", "audio"}},
		"timestamp":         {Kind: "Date", DefaultValue: "now", Required: false},
	},
	"ChatMessageStates": map[string]CollectionFieldConfig{
		"id":                {Kind: "ID", DefaultValue: nil, Required: false},
		"tenantId":          {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "Tenant", Key: "id"}},
		"chatMessageId":     {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "ChatMessage", Key: "id"}},
		"chatGroupMemberId": {Kind: "ID", DefaultValue: nil, Required: false, ForeignKey: CollectionFieldConfigForeignKey{Model: "ChatGroupMember", Key: "id"}},
		"sent":              {Kind: "Boolean", DefaultValue: false, Required: false},
		"sentDate":          {Kind: "Date", DefaultValue: nil, Required: false},
		"received":          {Kind: "Boolean", DefaultValue: false, Required: false},
		"receivedDate":      {Kind: "Date", DefaultValue: nil, Required: false},
		"opened":            {Kind: "Boolean", DefaultValue: false, Required: false},
		"openedDate":        {Kind: "Date", DefaultValue: nil, Required: false},
		"timestamp":         {Kind: "Date", DefaultValue: "now", Required: false},
	},
}
